dataset:
  root: data
  task: 3
image-model:
  enabled: true
  feat-dim: 2048
  fine-tune: false
  grid:
  - 7
  - 7
  name: resnet50
model:
  embed-dim: 1024
  feedforward-dim: 1024
  name: dual-transformer
  num-decoder-layers: 4
  num-encoder-layers: 4
text-model:
  extraction-hidden-layer: 10
  fine-tune: false
  name: roberta
  pretrain: roberta-base
  word-dim: 768
training:
  balanced-sampling: false
  bs: 8
  gamma: 0.1
  grad-clip: 2.0
  lr: 5.0e-05
  milestones: [5, 10, 15, 20, 25]
  pretrained-modules-lr: 5.0e-06
  scheduler: steplr
